language: cpp

matrix:
  include:
    - os: osx
      before_install:
        - brew update
        - brew upgrade cmake
        - brew install cmake

    - os: linux
      dist: trusty
      before_install:
        - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
        - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
        - CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
        - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
        - cd ..

script:
  - mkdir build && cd build && cmake .. && cmake --build .

notifications:
  email:
    recipients:
      - philippe.groarke@gmail.com
    on_success: never
    on_failure: always
