
env:
   global:
     - CONAN_REFERENCE: "ns_getopt/1.0.0"
     - CONAN_USERNAME: "p-groarke"
     - CONAN_LOGIN_USERNAME: "p-groarke"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/p-groarke/conan-public"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic

matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7

      - <<: *osx
        osx_image: xcode9
        env: CONAN_APPLE_CLANG_VERSIONS=9.0
        before_install:
        - brew update
        - brew upgrade cmake
        - brew install cmake

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh

notifications:
  email:
    on_success: never
    on_failure: always