build: false
init:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "ns_getopt/1.0.0"
    CONAN_USERNAME: "p-groarke"
    CONAN_LOGIN_USERNAME: "p-groarke"
    CONAN_CHANNEL: "stable"
    CONAN_UPLOAD: "https://api.bintray.com/conan/p-groarke/conan-public"
    CONAN_PASSWORD:
        secure: O+D/9uKIc8gU8yEvFug06FWBXkdy2wrqFTPR+K/utYEPc4KquI/3DXo2kiFFJ5OB
    BUILD_TESTING: "On"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug


install:
    - set PATH=%PATH%;%PYTHON%/Scripts/
    - pip.exe install conan --upgrade
    - pip.exe install conan_package_tools
    - conan user # It creates the conan data directory

test_script:
    - python build.py
